language: ruby
rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7
  - 2.1.10
  - 2.0.0
  - 1.9.3
  - 1.8.7

gemfile:
  - src/Gemfile

env:
  global:
    - TRAVIS_CI=1
    - CC_TEST_REPORTER_ID=b6978dc45c10964c6a8822122045fb70a1f0edb44994652664570428fcdbaa80

before_script:
  - cd src
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
