source 'https://rubygems.org'

unless ENV['TRAVIS_CI'] == '1'
  gem 'net-irc'
  gem 'ocra'

  WXRUBY_RUBY19_PLATFORMS = %w(x86-mingw32 x86-linux x86_64-linux)
  if RUBY_VERSION >= '1.9' && WXRUBY_RUBY19_PLATFORMS.include?(RUBY_PLATFORM)
    gem 'wxruby-ruby19', '2.0.0'
  end
end

group :development, :test do
  if RUBY_VERSION < '1.9'
    gem 'rake', '~> 10.5'
    gem 'test-unit', '1.2.3'
  else
    gem 'rake'
    gem 'test-unit'
    gem 'simplecov', :require => false
  end
end
